# Generated by Django 4.2.5 on 2025-05-04 10:56

from django.db import migrations
import random
from django.utils import timezone

def create_authors_and_books(apps,something):
    Author = apps.get_model('app', 'Author')
    Book = apps.get_model('app', 'Book')
    authors = [
        Author.objects.create(first_name="erfan", last_name="aliyavari", age=26, national_id="1234567890"),
        Author.objects.create(first_name="maryam", last_name="khani", age=30, national_id="0987654321"),
        Author.objects.create(first_name="sasan", last_name="dawjones", age=18, national_id="1122334455")
    ]
    books = ['test', 'test2', 'test3', 'test4', 'test5', 'test6']
    current_year = timezone.now().year
    random_years = random.sample(range(current_year - 100, current_year), len(books))
    for index, item in enumerate(books):
        Book.objects.create(title=item, publication_year=random_years[index], author=random.choice(authors))

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_authors_and_books),
    ]
