# Generated by Django 4.2.5 on 2025-05-06 10:41

from django.db import migrations, models
import django.db.models.deletion

def populate_default_category(apps, schema_editor):
    BookCategory = apps.get_model('app', 'BookCategory')
    Book = apps.get_model('app', 'Book')

    category, created = BookCategory.objects.get_or_create(title='Uncategorized')

    # Assign the "Uncategorized" category to all existing books that don't have a category
    Book.objects.filter(category__isnull=True).update(category=category)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250504_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='app.bookcategory'),
        ),
        migrations.RunPython(populate_default_category)
    ]
