# Generated by Django 4.2.5 on 2025-05-13 11:32

from django.db import migrations, models
import django.db.models.deletion


def populate_countries(apps, schema_editor):
    from django_countries import countries
    Country = apps.get_model('app', 'Country')

    for code, name in countries:
        Country.objects.create(name=name)


def fix_null_countries(apps, schema_editor):
    Author = apps.get_model('app', 'Author')
    Country = apps.get_model('app', 'Country')
    iran = Country.objects.get(name='Iran')
    authors = Author.objects.filter(country__isnull=True).update(country=iran)


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0011_alter_purchase_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books',
                                    to='app.bookcategory'),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authors',
                                    to='app.country'),
        ),
        migrations.RunPython(populate_countries),
        migrations.RunPython(fix_null_countries),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors',
                                    to='app.country'),
        ),
    ]
