# Generated by Django 4.2.5 on 2025-05-17 12:45

from django.db import migrations


def creating_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Moderator')
    Group.objects.get_or_create(name='Operator')
    Group.objects.get_or_create(name='Admin')

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Moderator').delete()
    Group.objects.filter(name='Operator').delete()
    Group.objects.filter(name='Admin').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0012_country_alter_book_category_author_country'),
    ]

    operations = [
        migrations.RunPython(creating_groups, remove_groups),
    ]
