# Generated by Django 4.2.5 on 2025-05-19 13:53

from django.db import migrations

def assign_group_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    operator_group = Group.objects.get(name='Operator')
    moderator_group = Group.objects.get(name='Moderator')
    admin_group = Group.objects.get(name='Admin')

    perm_operator = Permission.objects.get(codename='add_author')
    perm_moderator = Permission.objects.get(codename='change_author')
    perm_admin = Permission.objects.get(codename='delete_author')

    operator_group.permissions.add(perm_operator)
    moderator_group.permissions.add(perm_moderator)
    admin_group.permissions.add(perm_admin)

def remove_group_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    operator_group = Group.objects.get(name='Operator')
    moderator_group = Group.objects.get(name='Moderator')
    admin_group = Group.objects.get(name='Admin')

    perm_operator = Permission.objects.get(codename='add_author')
    perm_moderator = Permission.objects.get(codename='change_author')
    perm_admin = Permission.objects.get(codename='delete_author')

    operator_group.permissions.remove(perm_operator)
    moderator_group.permissions.remove(perm_moderator)
    admin_group.permissions.remove(perm_admin)
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_userprofile_avatar'),
    ]

    operations = [
        migrations.RunPython(assign_group_permissions, remove_group_permissions),
    ]
