# Generated by Django 4.2.5 on 2025-06-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20250519_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='color_format',
            field=models.CharField(default='bw', max_length=100),
            preserve_default=False,
        ),
    ]
