from django.contrib import admin
from django.urls import path, include
from .views import (
    AuthorListView,
    AuthorCreateView,
    AuthorUpdateView,
    AuthorDeleteView,
    AuthorDetailView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
    AuthorBookCountView,
    AuthorBookMixinView,
    AuthorBookTreeView,
    AuthorBookPieView,
    IndexView,
    CustomLoginView,
    CustomLogoutView,
    BookCategoryListView,
    BookCategoryCreateView,
    BookCategoryUpdateView,
    BookCategoryDeleteView,
    # AuthorSlickView
)


# author_book_tree_json,
urlpatterns = [
    path("", AuthorListView.as_view(), name="home"),
    path("add_author", AuthorCreateView.as_view(), name="add_author"),
    path("edit_author/<int:pk>", AuthorUpdateView.as_view(), name="edit_author"),
    path("delete_author/<int:pk>", AuthorDeleteView.as_view(), name="delete_author"),
    path("author_detail/<int:pk>", AuthorDetailView.as_view(), name="author_detail"),
    path("add_book/<int:pk>", BookCreateView.as_view(), name="add_book"),
    path("edit_book/<int:pk>", BookUpdateView.as_view(), name="edit_book"),
    path("delete_book/<int:pk>", BookDeleteView.as_view(), name="delete_book"),
    path("author_bookcount", AuthorBookCountView.as_view(), name="authorbookcount"),
    path("author_bookmixin", AuthorBookMixinView.as_view(), name="authorbookmixin"),
    path('authors-tree/', AuthorBookTreeView.as_view(), name='author-book-tree'),
    # path('authors-tree/json/', author_book_tree_json, name='author-book-tree-json'),
    path('standalone_pie/', AuthorBookPieView.as_view(), name='standalone_pie'),
    # path('authorslick', AuthorSlickView.as_view(), name='authorslick'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('index', IndexView.as_view(), name='index'),
    path('categories/', BookCategoryListView.as_view(), name='bookcategory_list'),
    path('categories/add/', BookCategoryCreateView.as_view(), name='bookcategory_create'),
    path('categories/edit/<int:pk>/', BookCategoryUpdateView.as_view(), name='bookcategory_edit'),
    path('categories/delete/<int:pk>/', BookCategoryDeleteView.as_view(), name='bookcategory_delete'),
]
