from django.contrib import admin
from django.urls import path, include
from .views import (
    AuthorListView,
    AuthorCreateView,
    AuthorUpdateView,
    AuthorDeleteView,
    AuthorDetailView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
    AuthorBookCountView,
    AuthorBookMixinView,
    AuthorBookTreeView,
    AuthorBookPieView,
    IndexView,
    CustomLoginView,
    CustomLogoutView,
    BookCategoryListView,
    BookCategoryCreateView,
    BookCategoryUpdateView,
    BookCategoryDeleteView,
    SignUpCreateView,
    BooksListView,
    BookSelectView,
    BookPurchaseView,
    ForgotPasswordFormView,
    ResetPasswordFormView,
    ConfirmCodeFormView,
    SmsLoginView,
    SmsLoginConfirmCodeFormView,
    Login2FAView,
    Login2FAConfirmView,
    Library2FALoginView,
    TestView,
    PurchaseView,
)
from .reports import BookSalesReport, BookPublicationReport, AuthorByCountryReport

# author_book_tree_json,
urlpatterns = [
    path("", AuthorListView.as_view(), name="home"),
    path("add_author", AuthorCreateView.as_view(), name="add_author"),
    path("edit_author/<int:pk>", AuthorUpdateView.as_view(), name="edit_author"),
    path("delete_author/<int:pk>", AuthorDeleteView.as_view(), name="delete_author"),
    path("author_detail/<int:pk>", AuthorDetailView.as_view(), name="author_detail"),
    path("add_book/<int:pk>", BookCreateView.as_view(), name="add_book"),
    path("edit_book/<int:pk>", BookUpdateView.as_view(), name="edit_book"),
    path("delete_book/<int:pk>", BookDeleteView.as_view(), name="delete_book"),
    path("author_bookcount", AuthorBookCountView.as_view(), name="authorbookcount"),
    path("author_bookmixin", AuthorBookMixinView.as_view(), name="authorbookmixin"),
    path('authors-tree/', AuthorBookTreeView.as_view(), name='author-book-tree'),
    path('standalone_pie/', AuthorBookPieView.as_view(), name='standalone_pie'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('index', IndexView.as_view(), name='index'),
    path('categories/', BookCategoryListView.as_view(), name='bookcategory_list'),
    path('categories/add/', BookCategoryCreateView.as_view(), name='bookcategory_create'),
    path('categories/edit/<int:pk>/', BookCategoryUpdateView.as_view(), name='bookcategory_edit'),
    path('categories/delete/<int:pk>/', BookCategoryDeleteView.as_view(), name='bookcategory_delete'),
    path('signup', SignUpCreateView.as_view(), name='signup'),
    path('select2/', include('django_select2.urls')),
    path('booklist/', BooksListView.as_view(), name='booklist'),
    path('bookselect/', BookSelectView.as_view(), name='bookselect'),
    path('purchase_book/<int:pk>/', BookPurchaseView.as_view(), name='purchase_page'),
    path('forgotpassword/', ForgotPasswordFormView.as_view(), name='forgotpassword'),
    path('resetpassword/', ResetPasswordFormView.as_view(), name='resetpassword'),
    path('confirm_code/', ConfirmCodeFormView.as_view(), name='confirm_code'),
    path('smslogin/', SmsLoginView.as_view(), name='smslogin'),
    path('smsloginconfirm/', SmsLoginConfirmCodeFormView.as_view(), name='smsloginconfirm'),
    path('login2fa/', Login2FAView.as_view(), name='login2fa'),
    path('login2faconfirm/', Login2FAConfirmView.as_view(), name='login2faconfirm'),
    path('librarylogin/login/', Library2FALoginView.as_view(), name='librarylogin'),
    path('tests/', TestView.as_view(), name='test'),
    path('purchaselist/', PurchaseView.as_view(), name='purchaselist'),
    path('reports/book-sales/', BookSalesReport.as_view(), name='book-sales-report'),
    path('reports/book-publication/', BookPublicationReport.as_view(), name='book-publication-report'),
    path('reports/authors-by-country/', AuthorByCountryReport.as_view(), name='authors-by-country-report'),
]
